---

- name: systemd_resolved | Disabling and Stopping systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true
  register: _dnsmasq_systemd_resolved_disabled
  notify:
    - restart dnsmasq

- name: systemd_resolved | Checking If /etc/resolv.conf Exists
  stat:
    path: /etc/resolv.conf
  register: _dnsmasq_resolv_conf

- name: systemd_resolved | Removing Existing /etc/resolv.conf If symlink
  file:
    path: /etc/resolv.conf
    state: absent
  become: true
  register: _dnsmasq_resolv_conf_removed
  when:
    - _dnsmasq_systemd_resolved_disabled['changed']
    - _dnsmasq_resolv_conf['stat']['islnk']

- name: systemd_resolved | Creating /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: o=rw,g=r,o=r
  become: true
  notify:
    - restart dnsmasq
  when: ansible_virtualization_type != "docker"
